# Database
db.File=jdbc:sqlite:Storage\\Database\\AirPort.sqlite
db.User=usuario
db.Pass=secreta

# # Datafile
df.AntCoor=storage\\DataFiles\\pat_mic.csv
df.AntNest=storage\\DataFiles\\AntNest.txt
df.AntFood=storage\\DataFiles\\AntFood.txt

# Logs
df.logFile=Storage/Logs/AppErrors.log

# Resource
res.img.Main=   /Infrastructure/resources/img/Main.png
res.img.Logo=   /Infrastructure/resources/img/Logo.png
res.img.Splash= /Infrastructure/resources/img/Splash.png

# RFID Arduino
rfid.port=COM7          # Cambiar según tu puerto (COM3, COM4, etc.)
rfid.baudrate=9600
rfid.timeout=5000